export const gamesArray = [
    {
        id: 1,
        title: 'Wingspan',
        game_type: 'Engine-Building, Card Game',
        description: 'Wingspan is a competitive, medium-weight, card-driven, engine-building board game where players take on the role of bird enthusiasts working to attract the best birds to their wildlife preserves. The game is played over four rounds, where players collect food, lay eggs, and draw bird cards in order to build their engine and score points.',
        company: 'Stonemaier Games',
        players_required: 5,
        time_required: 70,
        published: 2019,
        image: 'https://files.ekmcdn.com/boardgameguru/images/wingspan-2nd-edition-63289-p.jpg',
    },
    {
        id: 2,
        title: 'Root',
        game_type: 'Area Control, Strategy, Adventure',
        description: 'Root is a strategy game of woodland might and right where players take on the role of asymmetrical factions vying for control of a vast forest. Each faction plays differently and has its own unique way to interact with the other players, leading to an ever-changing strategic experience.',
        company: 'Leder Games',
        players_required: 4,
        time_required: 90,
        published: 2018,
        image: 'https://cf.geekdo-images.com/t6d0I4JhJcBQ3gq1F-VSfw__original/img/TkzOclg_zV3XXL-oetKmLNAmz5I=/0x0/filters:format(webp)/pic4043480.jpg'
    },
    {
        id: 3,
        title: 'Catan',
        game_type: 'Strategy, Resource Management, Trading',
        description: 'Catan (formerly The Settlers of Catan) is a popular strategy board game where players collect and trade resources to build settlements, cities, and roads in a race to reach 10 victory points. The game involves resource management, trading, and building strategies.',
        company: 'Catan Studio',
        players_required: 4,
        time_required: 120,
        published: 1995,
        image: 'https://cf.geekdo-images.com/8Xb_8BdxedI0mybns5YZaw__original/img/MrdnDQGbxyIgj-Jne-rlxTyC-QE=/0x0/filters:format(webp)/pic1577559.jpg'
    },
    {
        id: 4,
        title: 'Codenames',
        game_type: 'Word Game, Party Game, Social Deduction',
        description: 'Codenames is a social word game where two teams of spymasters give one-word clues to their teams to guess the words that correspond to their agents on the board. It\'s a fun and quick game that involves deduction and creativity, ideal for parties.',
        company: 'Czech Games Edition',
        players_required: 8,
        time_required: 60,
        published: 2015,
        image: 'https://cf.geekdo-images.com/BZjXYbxjm9zyYBOg9taFvQ__original/img/RF_qzIt8vf2q8Sry9EY8-34OTpc=/0x0/filters:format(webp)/pic2437169.jpg'
    },
    {
        id: 5,
        title: 'Monopoly Deluxe Edition',
        game_type: 'Strategy, Economic',
        description: 'Monopoly Deluxe Edition is a high-quality version of the classic Monopoly game, featuring a deluxe board, luxury playing pieces, and a smooth, updated playing experience. Players aim to buy, sell, and trade properties to accumulate wealth and bankrupt their opponents.',
        company: 'Hasbro',
        players_required: 6,
        time_required: 120,
        published: 1997,
        image: 'https://cf.geekdo-images.com/xjK2feN8MPlOEK3-aWlwlg__original/img/aSyQccRmZGvG6Z9d-hGRz-LG1l8=/0x0/filters:format(webp)/pic3596357.jpg'
    },
    {
        id: 6,
        title: 'Flamecraft',
        game_type: 'Strategy, Engine-Building, Fantasy',
        description: 'Flamecraft is a worker placement game set in a magical world where players take on the role of artisans, crafting powerful items with the help of adorable dragons. It features a unique theme and charming artwork while offering deep strategic gameplay.',
        company: 'Cardboard Alchemy',
        players_required: 5,
        time_required: 60,
        published: 2022,
        image: 'https://cf.geekdo-images.com/qZK8o1_Kf4H6gk2AnruUPg__original/img/kV0UR_tjpcpt-K_cZySnl0DYoH8=/0x0/filters:format(webp)/pic7025020.jpg'
    },
    {
        id: 7,
        title: 'Cards Against Humanity',
        game_type: 'Party Game, Social Deduction, Word Game',
        description: 'Cards Against Humanity is a party game in which players fill in blanks of incomplete sentences using cards with humorous or controversial phrases. It is designed for mature players and is known for its irreverent humor.',
        company: 'Cards Against Humanity LLC',
        players_required: 20,
        time_required: 60,
        published: 2011,
        image: 'https://cf.geekdo-images.com/7tH2A1m_9gffXa3mAhI1Mw__original/img/VfT-B8cR1gJ-8ezqxZdAqEedFjk=/0x0/filters:format(webp)/pic913106.jpg'
    },
    {
        id: 8,
        title: 'Bananagrams',
        game_type: 'Word Game, Party Game',
        description: 'Bananagrams is a fast-paced word game where players race to build their own crossword grid using letter tiles. The game is quick, easy to learn, and great for parties.',
        company: 'Bananagrams Inc.',
        players_required: 8,
        time_required: 30,
        published: 2006,
        image: 'https://cf.geekdo-images.com/e0EgoBv0DCiv9Gb-V2kdGg__original/img/hg62GzBcn7jZ4m00jlQLN9F28bI=/0x0/filters:format(webp)/pic478410.jpg'
    },
    {
        id: 9,
        title: 'Sounds Fishy',
        game_type: 'Party Game, Social Deduction',
        description: 'In Sounds Fishy, players take turns being the "Liar" who has to make up a story about a given topic while the other players try to guess if the story is true or a lie. It\'s a fun and lighthearted game of bluffing and deception.',
        company: 'Big Potato Games',
        players_required: 6,
        time_required: 30,
        published: 2021,
        image: 'https://cf.geekdo-images.com/3n0vqrzvkw3BHK2TK88eyw__original/img/hkz23M9wKvNCvGp0pVNOz7Z76Ho=/0x0/filters:format(webp)/pic7026331.jpg'
    },
    {
        id: 10,
        title: 'Ticket to Ride: Europe',
        game_type: 'Strategy, Route Building, Family Game',
        description: 'Ticket to Ride: Europe is a variation of the classic Ticket to Ride game, where players build train routes across Europe. The game introduces tunnels, ferries, and stations, adding extra layers of strategy and excitement.',
        company: 'Days of Wonder',
        players_required: 5,
        time_required: 60,
        published: 2005,
        image: 'https://cf.geekdo-images.com/-1wVp6bpSLoF5gZ-x99Mkw__original/img/BzHhKNkqUBeesg48TjveVpi6S9Y=/0x0/filters:format(webp)/pic1872522.jpg'
    },
    {
        id: 11,
        title: 'Clue',
        game_type: 'Deduction, Mystery',
        description: 'Clue is a classic murder mystery board game where players must deduce who committed the murder, with what weapon, and in which room. The game involves logical thinking and deduction as players gather clues and eliminate possibilities.',
        company: 'Hasbro',
        players_required: 6,
        time_required: 60,
        published: 1949,
        image: 'https://cf.geekdo-images.com/ahPQE-DiczkDtbKTV9OZ4g__original/img/BYsAx5uXKujfJ5lZa4-JO6aA5iA=/0x0/filters:format(webp)/pic2019846.jpg'
    },
        {
        id: 12,
        name: 'Scrabble',
        game_type: 'Word Game',
        description: 'Scrabble is a classic word game where players use letter tiles to form words on a game board. Points are scored based on the letter values and the placement of words on premium squares.',
        publisher: 'Hasbro',
        players: 4,
        playtime: 60,
        year: 1938,
        image_url: 'https://cf.geekdo-images.com/7Ojo1fuDLfL0AL4_zQ9Gbw__original/img/6n8F3axjC7S7dMz7hxuVKETnS9M=/0x0/filters:format(webp)/pic3579215.jpg'
    },
    {
        id: 13,
        name: 'Hues and Cues',
        game_type: 'Party Game, Word Game, Color Recognition',
        description: 'In Hues and Cues, players give and guess clues based on colors to try to identify a particular hue on the board. It’s a fun and challenging game that tests your color perception and your ability to communicate it effectively to others.',
        publisher: 'The OP',
        players: 10,
        playtime: 45,
        year: 2020,
        image_url: 'https://cf.geekdo-images.com/udt5gD-9gtAgNNwm6m7PpA__original/img/9PA6hNfu7gR8ZkjmhFYhl2gk3YM=/0x0/filters:format(webp)/pic5083284.jpg'
    },
    {
        id: 14,
        name: 'Quoridor',
        game_type: 'Abstract Strategy, Grid Movement',
        description: 'Quoridor is an abstract strategy game where players race to move their pawn to the opposite side of the board. Players can block each other\'s paths using walls, creating a tense and strategic game of positioning.',
        publisher: 'Gigamic',
        players: 4,
        playtime: 30,
        year: 1997,
        image_url: 'https://cf.geekdo-images.com/8eWbZYjr9M4eFwz1h3Onvw__original/img/PITG9F0ykiwV9O2Vsn5hAY7sd2c=/0x0/filters:format(webp)/pic1366890.jpg'
    },
    {
        id: 15,
        name: 'Pandemic',
        game_type: 'Cooperative, Strategy, Disease Simulation',
        description: 'Pandemic is a cooperative strategy game where players work together to stop the spread of diseases around the world. Players take on different roles and must strategize to find cures and prevent outbreaks before time runs out.',
        publisher: 'Z-Man Games',
        players: 4,
        playtime: 60,
        year: 2008,
        image_url: 'https://cf.geekdo-images.com/3U2n_FekbpHNR4WjvjYw0Q__original/img/8Txl-F6YsG2wN0T7pSPrbz1frKw=/0x0/filters:format(webp)/pic1275735.jpg'
    },
    {
        id: 16,
        name: 'Articulate',
        game_type: 'Party Game, Word Game, Communication',
        description: 'Articulate is a fast-paced word guessing game where players describe words without saying them directly. The aim is to get your team to guess as many words as possible within a set time limit.',
        publisher: 'Drumond Park',
        players: 20,
        playtime: 60,
        year: 1992,
        image_url: 'https://cf.geekdo-images.com/Yz_51lreSyzO0DtS3p92Yw__original/img/gUB7TS7QsY4e8Onj3wa4T0O0RLg=/0x0/filters:format(webp)/pic3356710.jpg'
    },
    {
        id: 17,
        name: 'Wavelength',
        game_type: 'Party Game, Social Deduction, Communication',
        description: 'Wavelength is a social guessing game where players try to get their teammates to guess a position on a spectrum between two extremes. It’s about giving clues that will be interpreted accurately by your team while understanding their thought process.',
        publisher: 'Palm Court',
        players: 12,
        playtime: 45,
        year: 2019,
        image_url: 'https://cf.geekdo-images.com/T1OkB_7Vcl57yqJbFh-1lg__original/img/TzpEKzM-hysp6kBxXzzVbwbeKXI=/0x0/filters:format(webp)/pic4961337.jpg'
    },
    {
        id: 18,
        name: 'Calico',
        game_type: 'Strategy, Tile-Laying, Puzzle',
        description: 'Calico is a tile-laying game where players create beautiful quilts by placing colorful tiles in a strategic manner. The goal is to complete patterns and meet the specific goals of the game while competing for the best quilt design.',
        publisher: 'Flatout Games',
        players: 4,
        playtime: 45,
        year: 2020,
        image_url: 'https://cf.geekdo-images.com/i0B37U3LthvhgOU0Mmcjkw__original/img/oZX9MLe9HHiPj-2R6Gh-X86wnl8=/0x0/filters:format(webp)/pic5769861.jpg'
    },
    {
        id: 19,
        name: 'Mysterium',
        game_type: 'Cooperative, Social Deduction, Mystery',
        description: 'Mysterium is a cooperative game where one player takes the role of a ghost trying to communicate the details of their murder to the other players. Using abstract vision cards, the ghost provides clues for the other players to deduce the correct combination of suspect, weapon, and location.',
        publisher: 'Libellud',
        players: 7,
        playtime: 60,
        year: 2015,
        image_url: 'https://cf.geekdo-images.com/5r5niLmeYo-VocgO6gEzYw__original/img/7Fw1ftckVdughqDXb1h9VLeBzfs=/0x0/filters:format(webp)/pic2805751.jpg'
    }
];